[allowlist]
description = "Merged allowlist"
rules = [
  "gitlab-pat",
  "private-key",
  "jwt"
]
paths = [
  "docs/docs/installation/gitlab.md",
  "docs/docs/installation/github.md",
  "README.md",
  "pr_agent/settings/.secrets_template.toml"
]
